# Generated by Django 5.2.8 on 2025-11-25 13:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('meal_type', models.CharField(max_length=50)),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('calories', models.FloatField(default=0.0)),
                ('tags', models.TextField(blank=True, default='')),
                ('steps', models.JSONField(blank=True, default=list)),
                ('n_steps', models.IntegerField(default=0)),
                ('n_ingredients', models.IntegerField(default=0)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDietPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='diet_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('min_calories_per_day', models.FloatField(default=1500, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)])),
                ('max_calories_per_day', models.FloatField(default=2500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('meals_per_day', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('min_protein_per_day', models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('max_protein_per_day', models.FloatField(default=150, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('min_carbs_per_day', models.FloatField(default=150, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('max_carbs_per_day', models.FloatField(default=300, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('min_fat_per_day', models.FloatField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('max_fat_per_day', models.FloatField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('excluded_ingredients', models.JSONField(blank=True, default=list)),
                ('diet_type', models.CharField(choices=[('standard', 'Standardowa'), ('vegetarian', 'Wegetariańska'), ('vegan', 'Wegańska')], default='standard', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('user', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('recipes', models.ManyToManyField(blank=True, related_name='daily_meals', to='api.recipe')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.weeklymealplan')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('weekly_plan', 'date')},
            },
        ),
    ]
