# Generated by Django 5.2.8 on 2025-12-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_keto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_low_carb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_pescetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdietpreferences',
            name='diet_type',
            field=models.CharField(choices=[('standard', 'Normal'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('low_carb', 'Gluten Free'), ('keto', 'Keto'), ('pescetarian', 'Pescetarian'), ('vegan', 'Vegan')], default='standard', max_length=20),
        ),
    ]
