# Generated by Django 5.2.8 on 2025-12-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userreciperating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdietpreferences',
            name='diet_type',
            field=models.CharField(choices=[('standard', 'Normal'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('low_carb', 'Gluten Free'), ('keto', 'Keto'), ('pescetarian', 'Pescetarian'), ('vegan', 'Vegan')], default='standard', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserRecipeRating',
        ),
    ]
