# Generated by Django 5.2.8 on 2025-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userreciperating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdietpreferences',
            name='fitness_priority',
            field=models.CharField(choices=[('calories', 'Calories'), ('macros', 'Macros'), ('tags', 'Tags')], default='calories', max_length=20),
        ),
    ]
